# TCL File Generated by Component Editor 12.0
# Tue Jun 26 10:15:11 CEST 2012
# DO NOT MODIFY


#
# BiSS_Master "BiSS-Master" v1.0
# iC-Haus 2012.06.26.10:15:11
#
#

#
# request TCL package from ACDS 12.0
#
package require -exact qsys 12.0


#
# module BiSS_Master
#
set_module_property NAME mb119y
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Interface Protocols/Serial"
set_module_property AUTHOR iC-Haus
set_module_property DISPLAY_NAME BiSS-Master
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property DESCRIPTION "BiSS-Master IP"

#
# system info
#

#add_parameter ClockFrequency INTEGER 20000000
#set_parameter_property ClockFrequency DEFAULT_VALUE 20000000
#set_parameter_property ClockFrequency SYSTEM_INFO {CLOCK_RATE 20000000}

#
# file sets
#
add_fileset mb119y_synth QUARTUS_SYNTH quartus_synth_callback
set_fileset_property mb119y_synth TOP_LEVEL mb119y
#set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS true

add_fileset mb119y_sim SIM_VHDL sim_vhdl_callback
set_fileset_property mb119y_sim TOP_LEVEL mb119y

add_fileset mb119y_sim_verilog SIM_VERILOG sim_verilog_callback
set_fileset_property mb119y_sim TOP_LEVEL mb119y

proc quartus_synth_callback {entity_name} {
  add_fileset_file biss_synth.vhd     VHDL PATH hdl/biss_synth.vhd
  add_fileset_file biss_altera.vhd    VHDL PATH hdl/biss_altera.vhd
  add_fileset_file mb_vcomponents.vhd VHDL PATH hdl/mb_vcomponents.vhd
  add_fileset_file mbz101.vhd         VHDL PATH hdl/mbz101.vhd
  add_fileset_file mb1.vhd            VHDL PATH hdl/mb1.vhd
  add_fileset_file mbz201.vhd         VHDL PATH hdl/mbz201.vhd
  add_fileset_file mb2.vhd            VHDL PATH hdl/mb2.vhd
  add_fileset_file mb3.vhd            VHDL PATH hdl/mb3.vhd
  add_fileset_file mbz402.vhd         VHDL PATH hdl/mbz402.vhd
  add_fileset_file mbz401.vhd         VHDL PATH hdl/mbz401.vhd
  add_fileset_file mb4.vhd            VHDL PATH hdl/mb4.vhd
  add_fileset_file mb5.vhd            VHDL PATH hdl/mb5.vhd
  add_fileset_file mb6.vhd            VHDL PATH hdl/mb6.vhd
  add_fileset_file mb7.vhd            VHDL PATH hdl/mb7.vhd
  add_fileset_file mb8.vhd            VHDL PATH hdl/mb8.vhd
  add_fileset_file mb9.vhd            VHDL PATH hdl/mb9.vhd
  add_fileset_file mba.vhd            VHDL PATH hdl/mba.vhd
  add_fileset_file mbb.vhd            VHDL PATH hdl/mbb.vhd
  add_fileset_file mbc.vhd            VHDL PATH hdl/mbc.vhd
  add_fileset_file mb0.vhd            VHDL PATH hdl/mb0.vhd
  add_fileset_file mb119y.vhd         VHDL PATH hdl/mb119y.vhd
  add_fileset_file mb0.ocp            OTHER PATH mb0.ocp
  #add_fileset_file mb119y.syn.mission.sdc SDC PATH sdc/mb119y.syn.mission.sdc
}

proc sim_vhdl_callback {entity_name} {
  add_fileset_file biss_synth.vhd     VHDL PATH hdl/biss_synth.vhd
  add_fileset_file biss_altera.vhd    VHDL PATH hdl/biss_altera.vhd
  add_fileset_file mb_vcomponents.vhd VHDL PATH hdl/mb_vcomponents.vhd
  add_fileset_file mbz101.vhd         VHDL PATH hdl/mbz101.vhd
  add_fileset_file mb1.vhd            VHDL PATH hdl/mb1.vhd
  add_fileset_file mbz201.vhd         VHDL PATH hdl/mbz201.vhd
  add_fileset_file mb2.vhd            VHDL PATH hdl/mb2.vhd
  add_fileset_file mb3.vhd            VHDL PATH hdl/mb3.vhd
  add_fileset_file mbz402.vhd         VHDL PATH hdl/mbz402.vhd
  add_fileset_file mbz401.vhd         VHDL PATH hdl/mbz401.vhd
  add_fileset_file mb4.vhd            VHDL PATH hdl/mb4.vhd
  add_fileset_file mb5.vhd            VHDL PATH hdl/mb5.vhd
  add_fileset_file mb6.vhd            VHDL PATH hdl/mb6.vhd
  add_fileset_file mb7.vhd            VHDL PATH hdl/mb7.vhd
  add_fileset_file mb8.vhd            VHDL PATH hdl/mb8.vhd
  add_fileset_file mb9.vhd            VHDL PATH hdl/mb9.vhd
  add_fileset_file mba.vhd            VHDL PATH hdl/mba.vhd
  add_fileset_file mbb.vhd            VHDL PATH hdl/mbb.vhd
  add_fileset_file mbc.vhd            VHDL PATH hdl/mbc.vhd
  add_fileset_file mb0.vhd            VHDL PATH hdl/mb0.vhd
  add_fileset_file mb119y.vhd         VHDL PATH hdl/mb119y.vhd
  add_fileset_file mc200_header.vhd   VHDL PATH hdl/mc200_header.vhd
  add_fileset_file mc200.vhd          VHDL PATH hdl/mc200.vhd
  add_fileset_file mc200_wrapper.vhd  VHDL PATH hdl/mc200_wrapper.vhd
}

proc sim_verilog_callback {entity_name} {
  add_fileset_file biss_synth.vhd     VHDL PATH hdl/biss_synth.vhd
  add_fileset_file biss_altera.vhd    VHDL PATH hdl/biss_altera.vhd
  add_fileset_file mb_vcomponents.vhd VHDL PATH hdl/mb_vcomponents.vhd
  add_fileset_file mbz101.vhd         VHDL PATH hdl/mbz101.vhd
  add_fileset_file mb1.vhd            VHDL PATH hdl/mb1.vhd
  add_fileset_file mbz201.vhd         VHDL PATH hdl/mbz201.vhd
  add_fileset_file mb2.vhd            VHDL PATH hdl/mb2.vhd
  add_fileset_file mb3.vhd            VHDL PATH hdl/mb3.vhd
  add_fileset_file mbz402.vhd         VHDL PATH hdl/mbz402.vhd
  add_fileset_file mbz401.vhd         VHDL PATH hdl/mbz401.vhd
  add_fileset_file mb4.vhd            VHDL PATH hdl/mb4.vhd
  add_fileset_file mb5.vhd            VHDL PATH hdl/mb5.vhd
  add_fileset_file mb6.vhd            VHDL PATH hdl/mb6.vhd
  add_fileset_file mb7.vhd            VHDL PATH hdl/mb7.vhd
  add_fileset_file mb8.vhd            VHDL PATH hdl/mb8.vhd
  add_fileset_file mb9.vhd            VHDL PATH hdl/mb9.vhd
  add_fileset_file mba.vhd            VHDL PATH hdl/mba.vhd
  add_fileset_file mbb.vhd            VHDL PATH hdl/mbb.vhd
  add_fileset_file mbc.vhd            VHDL PATH hdl/mbc.vhd
  add_fileset_file mb0.vhd            VHDL PATH hdl/mb0.vhd
  add_fileset_file mb119y.vhd         VHDL PATH hdl/mb119y.vhd
  add_fileset_file mc200_header.vhd   VHDL PATH hdl/mc200_header.vhd
  add_fileset_file mc200.vhd          VHDL PATH hdl/mc200.vhd
  add_fileset_file mc200_wrapper.vhd  VHDL PATH hdl/mc200_wrapper.vhd
}



set_module_property VALIDATION_CALLBACK     validate_mb119y
set_module_property ELABORATION_CALLBACK    elaborate_mb119y

#
# documentation links
#
add_documentation_link "IcHaus Weblink" "http://www.ichaus.de/"
#Add your own here...


#
# parameters
#
add_parameter Slaves INTEGER 8
set_parameter_property Slaves DEFAULT_VALUE 8
set_parameter_property Slaves DISPLAY_NAME "Number of logical data channels (Slaves)"
set_parameter_property Slaves TYPE INTEGER
set_parameter_property Slaves UNITS None
set_parameter_property Slaves ALLOWED_RANGES {1 2 3 4 5 6 7 8}
set_parameter_property Slaves HDL_PARAMETER true
set_parameter_property Slaves DESCRIPTION "REPLACE ME: Short description for tooltip on GUI"
set_parameter_property Slaves LONG_DESCRIPTION "REPLACE ME: Long description shown on HELP page"

add_parameter NumRegs INTEGER 64
set_parameter_property NumRegs DEFAULT_VALUE 64
set_parameter_property NumRegs DISPLAY_NAME "Number of Registers for Register access"
set_parameter_property NumRegs TYPE INTEGER
set_parameter_property NumRegs UNITS None
set_parameter_property NumRegs ALLOWED_RANGES {4 8 12 16 20 24 28 32 36 40 44 48 52 56 60 64}
set_parameter_property NumRegs HDL_PARAMETER true
set_parameter_property NumRegs DESCRIPTION "REPLACE ME: Short description for tooltip on GUI"
set_parameter_property NumRegs LONG_DESCRIPTION "REPLACE ME: Long description shown on HELP page"


#
# display items
#


#
# connection point clk
#
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true

add_interface_port clk csi_clk_clk clk Input 1


#
# connection point reset_reset
#
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true

add_interface_port reset csi_reset_reset_n reset_n Input 1


#
# connection point s1
#
add_interface s1 avalon end
set_interface_property s1 addressAlignment DYNAMIC
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 isMemoryDevice false
set_interface_property s1 isNonVolatileStorage false
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 printableDevice false
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true

add_interface_port s1 avs_s1_write_n write_n Input 1
add_interface_port s1 avs_s1_read_n read_n Input 1
add_interface_port s1 avs_s1_address address Input 6
add_interface_port s1 avs_s1_writedata writedata Input 32
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_chipselect_n chipselect_n Input 1


#
# connection point conduit_end_0
#
add_interface external conduit end
set_interface_property external associatedClock ""
set_interface_property external associatedReset ""
set_interface_property external ENABLED true

add_interface_port external coe_ch1_MA export Output 1
add_interface_port external coe_ch1_MO export Output 1
add_interface_port external coe_ch1_SL export Input 1
add_interface_port external coe_ch1_EOT export Output 1
add_interface_port external get_sens export Input 1



#
# connection point irq0
#
add_interface irq0 interrupt end
set_interface_property irq0 associatedAddressablePoint ""
set_interface_property irq0 associatedClock clk
set_interface_property irq0 associatedReset reset
set_interface_property irq0 ENABLED true

add_interface_port irq0 ins_irq0_irq irq Output 1

proc elaborate_mb119y {}  {
#  set_parameter_value Channels [expr [get_parameter_value Channels]>[get_parameter_value Slaves] ? [get_parameter_value Channels] : [get_parameter_value Slaves]]
}
proc validate_mb119y {}  {
  if {[get_parameter_value Slaves]>8} {
    send_message warning "Slaves wrong."
  }
}
