# TCL File Generated by Component Editor 11.1
# Fri Feb 17 14:37:44 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssg_emb_sd_adc "Sigma-Delta ADC Interface" v1.1
# | acroslan 2012.02.17.14:37:44
# | Motor Control Sigma-Delta ADC Interface
# | 
# | D:/project/Industrial/MotorControl/components/ssg_emb_sd_adc/hdl/ssg_emb_sd_adc.v
# | 
# |    ./ssg_emb_sd_adc.v syn, sim
# |    ./ssg_emb_sd_adc_dec128.v syn, sim
# |    ./ssg_emb_sd_adc_dec16.v syn, sim
# |    ./ssg_emb_sd_adc_diff.v syn, sim
# | 
# | 1.2	Move overcurent detection to adc clock domain to avoid clock crosing problems
# |		Add capture registers for overcurrent detection
# | 1.3  Synchronise control reg bits
# |      Tidy up some synthesis warnings
# | 1.4 Use shorter counter value when decimation rate is set to lower value so that
# |     conversion time is reduced
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssg_emb_sd_adc
# | 
set_module_property DESCRIPTION "Motor Control Sigma-Delta ADC Interface"
set_module_property NAME ssg_emb_sd_adc
set_module_property VERSION 1.4
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Motor Control Suite"
set_module_property AUTHOR acroslan
set_module_property DISPLAY_NAME "Sigma-Delta ADC Interface"
set_module_property TOP_LEVEL_HDL_FILE ssg_emb_sd_adc.v
set_module_property TOP_LEVEL_HDL_MODULE ssg_emb_sd_adc
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL FALSE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ssg_emb_sd_adc
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ssg_emb_sd_adc.v {SYNTHESIS SIMULATION}
add_file ssg_emb_sd_adc_dec128.v {SYNTHESIS SIMULATION}
add_file ssg_emb_sd_adc_dec16.v {SYNTHESIS SIMULATION}
add_file ssg_emb_sd_adc_diff.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point irq
# | 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint avalon_slave
set_interface_property irq associatedClock clock
set_interface_property irq associatedReset reset

set_interface_property irq ENABLED true

add_interface_port irq avs_irq irq Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave
# | 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0

set_interface_property avalon_slave ENABLED true

add_interface_port avalon_slave avs_write_n write_n Input 1
add_interface_port avalon_slave avs_read_n read_n Input 1
add_interface_port avalon_slave avs_address address Input 4
add_interface_port avalon_slave avs_writedata writedata Input 32
add_interface_port avalon_slave avs_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_adc
# | 
add_interface clock_adc clock end
set_interface_property clock_adc clockRate 0

set_interface_property clock_adc ENABLED true

add_interface_port clock_adc clk_adc clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point adc
# | 
add_interface adc conduit end

set_interface_property adc ENABLED true

add_interface_port adc sync_dat_u export Input 1
add_interface_port adc sync_dat_w export Input 1
add_interface_port adc overcurrent export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point start
# | 
add_interface start conduit end

set_interface_property start ENABLED true

add_interface_port start start export Input 1
# | 
# +-----------------------------------
