# TCL File Generated by Component Editor 11.1
# Fri Feb 17 15:10:13 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssg_emb_dsm "Drive System Monitor" v1.2
# | acroslan 2012.02.17.15:10:13
# | Drive System Monitor
# | 
# | D:/project/Industrial/MotorControl/components/ssg_emb_dsm/hdl/ssg_emb_dsm.v
# | 
# |    ./ssg_emb_dsm.v syn, sim
# | 
# | 1.2 extra IDLE state to DSM which can be used to disable the PWM 
# |     under software control 
# |     Correct operation of state machine so that (e1 | e3) term does not mask 
# |     remainder of state machine and prevent pwm being disable under fault condition.
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssg_emb_dsm
# | 
set_module_property DESCRIPTION "Drive System Monitor"
set_module_property NAME ssg_emb_dsm
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Motor Control Suite"
set_module_property AUTHOR acroslan
set_module_property DISPLAY_NAME "Drive System Monitor"
set_module_property TOP_LEVEL_HDL_FILE ssg_emb_dsm.v
set_module_property TOP_LEVEL_HDL_MODULE ssg_emb_dsm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL FALSE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ssg_emb_dsm
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ssg_emb_dsm.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
add_parameter init STD_LOGIC_VECTOR 0
set_parameter_property init DEFAULT_VALUE 0
set_parameter_property init DISPLAY_NAME init
set_parameter_property init WIDTH 4
set_parameter_property init TYPE STD_LOGIC_VECTOR
set_parameter_property init UNITS None
set_parameter_property init ALLOWED_RANGES 0:15
set_parameter_property init AFFECTS_GENERATION false
set_parameter_property init HDL_PARAMETER true
add_parameter prech STD_LOGIC_VECTOR 1
set_parameter_property prech DEFAULT_VALUE 1
set_parameter_property prech DISPLAY_NAME prech
set_parameter_property prech WIDTH 4
set_parameter_property prech TYPE STD_LOGIC_VECTOR
set_parameter_property prech UNITS None
set_parameter_property prech ALLOWED_RANGES 0:15
set_parameter_property prech AFFECTS_GENERATION false
set_parameter_property prech HDL_PARAMETER true
add_parameter prer STD_LOGIC_VECTOR 2
set_parameter_property prer DEFAULT_VALUE 2
set_parameter_property prer DISPLAY_NAME prer
set_parameter_property prer WIDTH 4
set_parameter_property prer TYPE STD_LOGIC_VECTOR
set_parameter_property prer UNITS None
set_parameter_property prer ALLOWED_RANGES 0:15
set_parameter_property prer AFFECTS_GENERATION false
set_parameter_property prer HDL_PARAMETER true
add_parameter run STD_LOGIC_VECTOR 3
set_parameter_property run DEFAULT_VALUE 3
set_parameter_property run DISPLAY_NAME run
set_parameter_property run WIDTH 4
set_parameter_property run TYPE STD_LOGIC_VECTOR
set_parameter_property run UNITS None
set_parameter_property run ALLOWED_RANGES 0:15
set_parameter_property run AFFECTS_GENERATION false
set_parameter_property run HDL_PARAMETER true
add_parameter error STD_LOGIC_VECTOR 4
set_parameter_property error DEFAULT_VALUE 4
set_parameter_property error DISPLAY_NAME error
set_parameter_property error WIDTH 4
set_parameter_property error TYPE STD_LOGIC_VECTOR
set_parameter_property error UNITS None
set_parameter_property error ALLOWED_RANGES 0:15
set_parameter_property error AFFECTS_GENERATION false
set_parameter_property error HDL_PARAMETER true
add_parameter pwm_disable STD_LOGIC_VECTOR 0
set_parameter_property pwm_disable DEFAULT_VALUE 0
set_parameter_property pwm_disable DISPLAY_NAME pwm_disable
set_parameter_property pwm_disable WIDTH 4
set_parameter_property pwm_disable TYPE STD_LOGIC_VECTOR
set_parameter_property pwm_disable UNITS None
set_parameter_property pwm_disable ALLOWED_RANGES 0:15
set_parameter_property pwm_disable AFFECTS_GENERATION false
set_parameter_property pwm_disable HDL_PARAMETER true
add_parameter pwm_enable STD_LOGIC_VECTOR 1
set_parameter_property pwm_enable DEFAULT_VALUE 1
set_parameter_property pwm_enable DISPLAY_NAME pwm_enable
set_parameter_property pwm_enable WIDTH 4
set_parameter_property pwm_enable TYPE STD_LOGIC_VECTOR
set_parameter_property pwm_enable UNITS None
set_parameter_property pwm_enable ALLOWED_RANGES 0:15
set_parameter_property pwm_enable AFFECTS_GENERATION false
set_parameter_property pwm_enable HDL_PARAMETER true
add_parameter pwm_lower STD_LOGIC_VECTOR 3
set_parameter_property pwm_lower DEFAULT_VALUE 3
set_parameter_property pwm_lower DISPLAY_NAME pwm_lower
set_parameter_property pwm_lower WIDTH 4
set_parameter_property pwm_lower TYPE STD_LOGIC_VECTOR
set_parameter_property pwm_lower UNITS None
set_parameter_property pwm_lower ALLOWED_RANGES 0:15
set_parameter_property pwm_lower AFFECTS_GENERATION false
set_parameter_property pwm_lower HDL_PARAMETER true
add_parameter pwm_both STD_LOGIC_VECTOR 7
set_parameter_property pwm_both DEFAULT_VALUE 7
set_parameter_property pwm_both DISPLAY_NAME pwm_both
set_parameter_property pwm_both WIDTH 4
set_parameter_property pwm_both TYPE STD_LOGIC_VECTOR
set_parameter_property pwm_both UNITS None
set_parameter_property pwm_both ALLOWED_RANGES 0:15
set_parameter_property pwm_both AFFECTS_GENERATION false
set_parameter_property pwm_both HDL_PARAMETER true
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avs_write_n write_n Input 1
add_interface_port avalon_slave_0 avs_read_n read_n Input 1
add_interface_port avalon_slave_0 avs_address address Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point monitor
# | 
add_interface monitor conduit end

set_interface_property monitor ENABLED true

add_interface_port monitor overcurrent export Input 1
add_interface_port monitor overvoltage export Input 1
add_interface_port monitor undervoltage export Input 1
add_interface_port monitor chopper export Input 1
add_interface_port monitor dc_link_clk_err export Input 1
add_interface_port monitor igbt_err export Input 1
add_interface_port monitor error_out export Output 1
add_interface_port monitor overcurrent_latch export Output 1
add_interface_port monitor overvoltage_latch export Output 1
add_interface_port monitor undervoltage_latch export Output 1
add_interface_port monitor dc_link_clk_err_latch export Output 1
add_interface_port monitor igbt_err_latch export Output 1
add_interface_port monitor chopper_latch export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm_control
# | 
add_interface pwm_control conduit end

set_interface_property pwm_control ENABLED true

add_interface_port pwm_control pwm_control export Output 3
# | 
# +-----------------------------------
