# TCL File Generated by Component Editor 11.1
# Fri Feb 17 15:07:15 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssg_emb_pwm "PWM Interface" v1.1
# | acroslan 2012.02.17.15:07:15
# | Motor Control PWN Interface
# | 
# | D:/project/Industrial/MotorControl/components/ssg_emb_pwm/hdl/ssg_emb_pwm.v
# | 
# |    ./ssg_emb_pwm.v syn, sim
# | 
# +-----------------------------------

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssg_emb_pwm
# | 
set_module_property DESCRIPTION "Motor Control PWN Interface"
set_module_property NAME ssg_emb_pwm
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Motor Control Suite"
set_module_property AUTHOR acroslan
set_module_property DISPLAY_NAME "PWM Interface"
set_module_property TOP_LEVEL_HDL_FILE ssg_emb_pwm.v
set_module_property TOP_LEVEL_HDL_MODULE ssg_emb_pwm
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL FALSE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ssg_emb_pwm
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ssg_emb_pwm.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avs_write_n write_n Input 1
add_interface_port avalon_slave_0 avs_read_n read_n Input 1
add_interface_port avalon_slave_0 avs_address address Input 4
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm
# | 
add_interface pwm conduit end

set_interface_property pwm ENABLED true

add_interface_port pwm carrier export Output 16
add_interface_port pwm carrier_latch export Output 1
add_interface_port pwm encoder_strobe_n export Output 1
add_interface_port pwm u_h export Output 1
add_interface_port pwm u_l export Output 1
add_interface_port pwm v_h export Output 1
add_interface_port pwm v_l export Output 1
add_interface_port pwm w_h export Output 1
add_interface_port pwm w_l export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sync_out
# | 
add_interface sync_out conduit end

set_interface_property sync_out ENABLED true

add_interface_port sync_out sync_out export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point start_adc
# | 
add_interface start_adc conduit end

set_interface_property start_adc ENABLED true

add_interface_port start_adc start_adc export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point sync_in
# | 
add_interface sync_in conduit end

set_interface_property sync_in ENABLED true

add_interface_port sync_in sync_in export Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point pwm_control
# | 
add_interface pwm_control conduit end

set_interface_property pwm_control ENABLED true

add_interface_port pwm_control pwm_control export Input 3
# | 
# +-----------------------------------
