# TCL File Generated by Component Editor 11.1
# Thu Mar 22 10:45:28 GMT 2012
# DO NOT MODIFY


# +-----------------------------------
# | 
# | ssg_emb_dc_ballast "DC Link Monitor" v1.0
# | acroslan 2012.03.22.10:45:28
# | DC Link Monitor
# | 
# | D:/project/motorControl/components/ssg_emb_dc_ballast/hdl/ssg_emb_dc_ballast.v
# | 
# |    ./ssg_emb_dc_ballast.v syn, sim
# |    ./ssg_emb_dc_ballast_dec128.v syn, sim
# |    ./ssg_emb_dc_ballast_diff.v syn, sim
# | 
# +-----------------------------------

# Version 1.1
# Make clock domain crossing more robust to allow better synthesis constraints to be applied
# Tidy up code to fix Quartus synthesis warnings

# +-----------------------------------
# | request TCL package from ACDS 11.0
# | 
package require -exact sopc 11.0
# | 
# +-----------------------------------

# +-----------------------------------
# | module ssg_emb_dc_ballast
# | 
set_module_property DESCRIPTION "DC Link Monitor"
set_module_property NAME ssg_emb_dc_ballast
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Motor Control Suite"
set_module_property AUTHOR acroslan
set_module_property DISPLAY_NAME "DC Link Monitor"
set_module_property TOP_LEVEL_HDL_FILE ssg_emb_dc_ballast.v
set_module_property TOP_LEVEL_HDL_MODULE ssg_emb_dc_ballast
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL FALSE
set_module_property STATIC_TOP_LEVEL_MODULE_NAME ssg_emb_dc_ballast
set_module_property FIX_110_VIP_PATH false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file ssg_emb_dc_ballast.v {SYNTHESIS SIMULATION}
add_file ssg_emb_dc_ballast_dec128.v {SYNTHESIS SIMULATION}
add_file ssg_emb_dc_ballast_diff.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | display items
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock
# | 
add_interface clock clock end
set_interface_property clock clockRate 0

set_interface_property clock ENABLED true

add_interface_port clock clk clk Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ENABLED true

add_interface_port avalon_slave_0 avs_write_n write_n Input 1
add_interface_port avalon_slave_0 avs_read_n read_n Input 1
add_interface_port avalon_slave_0 avs_address address Input 4
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point reset
# | 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT

set_interface_property reset ENABLED true

add_interface_port reset reset_n reset_n Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point status
# | 
add_interface status conduit end

set_interface_property status ENABLED true

add_interface_port status sync_dat export Input 1
add_interface_port status dc_link_enable export Input 1
add_interface_port status overvoltage export Output 1
add_interface_port status undervoltage export Output 1
add_interface_port status chopper export Output 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_adc
# | 
add_interface clock_adc clock end
set_interface_property clock_adc clockRate 0

set_interface_property clock_adc ENABLED true

add_interface_port clock_adc clk_adc clk Input 1
# | 
# +-----------------------------------
